name: Enrich roster images

on:
  workflow_dispatch:
  schedule:
    - cron: "27 8 * * *"

jobs:
  enrich-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run image enrichment
        env:
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
        run: |
          # Assuming your scraper already wrote sample_handguns.json
          python integrate_images.py --in sample_handguns.json --out handguns_with_images.json --sleep 0.7

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/ handguns_with_images.json
          git commit -m "Enrich images via image_resolver"
          git push
