name: Scrape DOJ handguns

on:
  workflow_dispatch:
  schedule:
    - cron: "17 8 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install playwright beautifulsoup4 lxml requests
          python -m playwright install --with-deps chromium

      - name: Scrape DOJ roster
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python update_handguns.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sample_handguns.json
          git commit -m "Update DOJ recently-added roster"
          git push
