name: Update Handgun JSON

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Playwright scraper
        run: python update_handguns.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add sample_handguns.json
          git diff --cached --quiet || git commit -m "Auto-update handgun list"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git remote -v
          git push origin HEAD:main

      - name: Upload debug screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: page_debug
          path: page_debug.png
